[tool.poetry]
name = "cassava-csv"
version = "0.5.1"
description = "Cassava is a package for reading, plotting and quality-checking CSV files."
authors = ["Paul Breen <pbree@bas.ac.uk>"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/paul-breen/cassava"
homepage = "https://github.com/paul-breen/cassava"
documentation = "https://github.com/paul-breen/cassava/blob/main/README.md"

# This is required because the cassava name is taken on PyPI, hence "name"
# above is different to the directory/module name
packages = [
    {include = "cassava"}
]

[tool.poetry.scripts]
cassava = "cassava.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.4.3"
blessed = "^1.18.1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
pytest-mock = "^3.0.0"
pdoc = "^16.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
